### ISSUE TITLE
Can't build on FreeBSD 12.0 because of rust -alsa

### ISSUE THREAD

**Issue by andoriyu** [Spotifyd/spotifyd#204]
Tried current stable, beta and mightly:

```
error[E0308]: mismatched types
  --> /home/andoriyu/.cargo/registry/src/github.com-1ecc6299db9ec823/alsa-0.2.1/src/poll.rs:43:51
   |
43 |     let r = unsafe { libc::poll(fds.as_mut_ptr(), fds.len() as libc::c_ulong, timeout as libc::c_int) };
   |                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^ expected u32, found u64

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: Could not compile `alsa`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

I understand that the issue is with alsa crate and not this one, but GitHub repo for rust-also looks very...abandoned?

**Comment by SimonPersson** [comment]
Sorry about that. Maybe using the `portaudio` or `pulseaudio` backends would be a better alternative anyway for FreeBSD?

**Comment by andoriyu** [comment]
Probably. Turns out there is already a version that uses `pulseaudio` in ports, so I'm good.
