### ISSUE TITLE
Error compiled with librespot

### ISSUE THREAD

**Issue by antonellocaroli** [Spotifyd/spotifyd#563]
I've been trying to fill it out, from now on, to the source of librespot.

But I get this error, I was really interested in solving the gapless problem:

Compiling librespot-protocol v0.1.1 (/tmp/librespot/protocol)
   Compiling librespot-core v0.1.1 (/tmp/librespot/core)
   Compiling librespot-audio v0.1.1 (/tmp/librespot/audio)
   Compiling librespot-metadata v0.1.1 (/tmp/librespot/metadata)
   Compiling librespot-playback v0.1.1 (/tmp/librespot/playback)
warning: unnecessary parentheses around type
  --> /tmp/librespot/playback/src/audio_backend/alsa.rs:28:42
   |
28 | fn open_device(dev_name: &str) -> Result<(PCM), Box<Error>> {
   |                                          ^^^^^ help: remove these parentheses
   |
   = note: `#[warn(unused_parens)]` on by default

warning: unnecessary parentheses around type
  --> /tmp/librespot/playback/src/mixer/alsamixer.rs:13:61
   |
13 |     fn map_volume(&self, set_volume: Option<u16>) -> Result<(u16), Box<dyn Error>> {
   |                                                             ^^^^^ help: remove these parentheses

   Compiling librespot-connect v0.1.1 (/tmp/librespot/connect)
   Compiling librespot v0.1.1 (/tmp/librespot)
   Compiling spotifyd v0.2.24 (/tmp/spotifyd)
**error[E0063]: missing field `gapless` in initializer of `librespot_playback::config::PlayerConfig`**
   --> src/config.rs:684:24
    |
684 |         player_config: PlayerConfig {
    |                        ^^^^^^^^^^^^ missing `gapless`

error[E0027]: pattern does not mention fields `play_request_id`, `position_ms`
  --> src/process.rs:67:9
   |
67 |         PlayerEvent::Started { track_id } => {
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing fields `play_request_id`, `position_ms`

error[E0027]: pattern does not mention field `play_request_id`
  --> src/process.rs:71:9
   |
71 |         PlayerEvent::Stopped { track_id } => {
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing field `play_request_id`

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0027, E0063.
For more information about an error, try `rustc --explain E0027`.
error: could not compile `spotifyd`.

To learn more, run the command again with --verbose.

**Comment by idofr** [comment]
I'm also having a problem with it.
Version 0.1.1 seems to generally be problematic, as it doesn't even compile its doc or shows the source files in the crate repo
https://docs.rs/crate/librespot-protocol/0.1.1

I'm getting the following error when trying to compile

```
error[E0308]: mismatched types
  --> /home/ido/.cargo/registry/src/github.com-1ecc6299db9ec823/librespot-protocol-0.1.1/build.rs:45:39
   |
45 |         let p = parse_and_typecheck(&["proto"], &[src]).expect("protoc");
   |                                       ^^^^^^^ expected struct `std::path::Path`, found `str`
   |
   = note: expected reference `&std::path::Path`
              found reference `&'static str`

error[E0308]: mismatched types
  --> /home/ido/.cargo/registry/src/github.com-1ecc6299db9ec823/librespot-protocol-0.1.1/build.rs:45:51
   |
45 |         let p = parse_and_typecheck(&["proto"], &[src]).expect("protoc");
   |                                                   ^^^ expected struct `std::path::Path`, found struct `std::string::Str  ing`
   |
   = note: expected reference `&std::path::Path`
              found reference `&std::string::String`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0308`.
error: could not compile `librespot-protocol`.

```

**Comment by jb55** [comment]
> @jb55 did you not have any problems when bumping up from 1.1 to 1.1.1 back in Feb?

no I did not

**Comment by idofr** [comment]
So all relevant issues in both repos seem to have been started in the last two weeks.... Lets see how this develops

**Comment by CPerezz** [comment]
It looks like the solution to this problem was already commited in 92cc28d.

I was experiencing the same issues with `cargo install spotifyd` and adding the `--locked`  flag solved everything as it is suggested in librespot-org/librespot#477

Should be the README updated in order to state that if you install `spotifyd` using `cargo install` fetching from crates.io the `--locked` file has to be added too?

**Comment by SirWindfield** [comment]
That would be ideal! Could you create a PR @CPerezz ? :)

**Comment by CPerezz** [comment]
Sure!
