### ISSUE TITLE
Spotifyd on System dbus ?

### ISSUE THREAD

**Issue by NNEU-1** [Spotifyd/spotifyd#944]
Hi,

is there any way of getting Spotifyd on the system DBus instead of the session one?

Thanks !

**Comment by eladyn** [comment]
In order to be able to use spotifyd on the System Bus, I just changed this line:
https://github.com/Spotifyd/spotifyd/blob/82bc875efc4e1b2e0e1c2e489e3dd4f2e6a5b97b/src/dbus_mpris.rs#L162
to
```rust
        Connection::get_private(BusType::System).expect("Failed to initialize DBus connection"),
```
and compiled spotifyd myself. I don't think that there is any config or compile time option for this.

Afterwards, I created an appropriate file in `/etc/dbus-1/system.d/` to allow spotifyd to use that Bus.

Hope this helps!

**Comment by NNEU-1** [comment]
Thanks for your reply !

I just tried it, but im getting the following error when compiling:
`| error[E0061]: this function takes 5 arguments but 4 arguments were supplied
|   --> src/main_loop.rs:71:19
|    |
| 71 |       Some(Box::new(DbusServer::new(
|    |                     ^^^^^^^^^^^^^^^ expected 5 arguments
| 72 |           session,
|    |           -------
| 73 |           handle,
|    |           ------
| 74 |           spirc,
|    |           -----
| 75 |           device_name,
|    |           ----------- supplied 4 arguments
|    |
|   ::: src/dbus_mpris.rs:63:5
|    |
| 63 | /     pub fn new(
| 64 | |         session: Session,
| 65 | |         handle: Handle,
| 66 | |         spirc: Rc<Spirc>,
| ...  |
| 80 | |         }
| 81 | |     }
|    | |_____- defined here
| 
| error: aborting due to previous error`

**Comment by eladyn** [comment]
I'm pretty sure that this was the only thing I changed to make it work.

Can you double-check that you have checked out a version of spotifyd that does compile without the change? Judging from the line numbers in your compiler errors, this doesn't seem to be the current master or tag 0.3.2.

**Comment by NNEU-1** [comment]
You were right, it works on 0.3.2.
I previously tried on 0.3.0.

Thanks !
