### ISSUE TITLE
Fails to build with Rust > 1.79

### ISSUE THREAD

**Issue by 0323pin** [Spotifyd/spotifyd#1308]
Please bump `time` to 0.3.36 or higher to fix build with Rust-1.80 and cut a new tag.

Else, building release fails with:
```
error[E0282]: type annotations needed for `Box<_>`
  --> /pbulk/work/audio/spotifyd/work/vendor/time-0.3.20/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++

For more information about this error, try `rustc --explain E0282`.
error: could not compile `time` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
*** Error code 101
```

Thanks!

**Comment by eladyn** [comment]
I will try to get to it during the weekend, but if you need it right now, you should just be able to do `cargo update`.

**Comment by 0323pin** [comment]
@eladyn Cheers, that would be appreciated.

>  if you need it right now, you should just be able to do cargo update

Yeah, I know that I could do that for personal use but, I'm asking this to fix the broken NetBSD package.

**Comment by davidgauch** [comment]
This issue can likely be closed.
I believe it was resolved in this PR:
https://github.com/Spotifyd/spotifyd/pull/1297

**Comment by 0323pin** [comment]
True, closing now. Thanks.
